#ifndef _IOC_BT_TTY_SDIO_H
#define _IOC_BT_TTY_SDIO_H

#include <asm/ioctls.h>
#include "bts_io_msg.h"

#define BTTTYSDIO_IOC_MAGIC     'H'

#define BTTTYSDIO_IOC_DLFW      _IOW(BTTTYSDIO_IOC_MAGIC,1,BTDLFW_Msg)
#define BTTTYSDIO_IOC_RMEM      _IOWR(BTTTYSDIO_IOC_MAGIC,2,BT_RWMem_Msg)
#define BTTTYSDIO_IOC_WMEM      _IOW(BTTTYSDIO_IOC_MAGIC,3,BT_RWMem_Msg)
#define BTTTYSDIO_IOC_RREG      _IOWR(BTTTYSDIO_IOC_MAGIC,4,BT_RWMem_Msg)
#define BTTTYSDIO_IOC_WREG      _IOW(BTTTYSDIO_IOC_MAGIC,5,BT_RWMem_Msg)
#define BTTTYSDIO_IOC_EINT      _IO(BTTTYSDIO_IOC_MAGIC,6)
#define BTTTYSDIO_IOC_CLK_ENA   _IO(BTTTYSDIO_IOC_MAGIC,7)
#define BTTTYSDIO_IOC_CLK_DIS   _IO(BTTTYSDIO_IOC_MAGIC,8)

#define BTTTYSDIO_IOC_LAST      BTTTYSDIO_IOC_EINT
#define BTTTYSDIO_IOC_MAX_NR    BTTTYSDIO_IOC_LAST

#endif  /* _IOC_BT_TTY_SDIO_H */
