/***************************************************************************//**
* File Name: cycfg_gatt_db.h
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.50.0.6117
*
********************************************************************************
* Copyright 2022 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS               0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME           0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE            0x2A01
#define __UUID_SERVICE_GENERIC_ATTRIBUTE            0x1801
#define __UUID_SERVICE_IMMEDIATE_ALERT              0x1802
#define __UUID_CHARACTERISTIC_ALERT_LEVEL           0x2A06

/* Service Generic Access */
#define HDLS_GAP                                    0x0001
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                        0x0002
#define HDLC_GAP_DEVICE_NAME_VALUE                  0x0003
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                         0x0004
#define HDLC_GAP_APPEARANCE_VALUE                   0x0005

/* Service Generic Attribute */
#define HDLS_GATT                                   0x0006

/* Service Immediate Alert */
#define HDLS_IAS                                    0x0007
/* Characteristic Alert Level */
#define HDLC_IAS_ALERT_LEVEL                        0x0008
#define HDLC_IAS_ALERT_LEVEL_VALUE                  0x0009

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_ias_alert_level[];
extern const uint16_t app_ias_alert_level_len;

#endif /* CYCFG_GATT_DB_H */
