/***************************************************************************//**
* File Name: cycfg_gap.c
*
* Description:
* BLE device's GAP configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.50.0.6117
*
********************************************************************************
* Copyright 2022 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gap.h"

/* Device address */
const wiced_bt_device_address_t cy_bt_device_address = {0x43, 0x01, 0x2C, 0x00, 0x1F, 0xAC};

const uint8_t cy_bt_adv_packet_elem_0[1] = { 0x06 };
const uint8_t cy_bt_adv_packet_elem_1[14] = { 0x46, 0x69, 0x6E, 0x64, 0x20, 0x4D, 0x65, 0x20, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74 };
const uint8_t cy_bt_adv_packet_elem_2[2] = { 0x00, 0x00 };
wiced_bt_ble_advert_elem_t cy_bt_adv_packet_data[] = 
{
    /* Flags */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_FLAG, 
        .len = 1, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_0, 
    },
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 14, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_1, 
    },
    /* Appearance */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_APPEARANCE, 
        .len = 2, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_2, 
    },
};
const uint8_t cy_bt_scan_resp_packet_elem_0[14] = { 0x46, 0x69, 0x6E, 0x64, 0x20, 0x4D, 0x65, 0x20, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74 };
const uint8_t cy_bt_scan_resp_packet_elem_1[7] = { 0x00, 0x43, 0x01, 0x2C, 0x00, 0x1F, 0xAC };
wiced_bt_ble_advert_elem_t cy_bt_scan_resp_packet_data[] = 
{
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 14, 
        .p_data = (uint8_t*)cy_bt_scan_resp_packet_elem_0, 
    },
    /* LE Bluetooth Device Address */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_LE_BD_ADDR, 
        .len = 7, 
        .p_data = (uint8_t*)cy_bt_scan_resp_packet_elem_1, 
    },
};
